openapi: 3.1.0
info:
  version: 1.0.0
  title: PhoneBook
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of PhoneBook app
servers:
  - url: http://127.0.0.1:3000
tags:
  - name: Contacts
    description: Operation with contacts.
paths:
  /contacts/{id}:
    get: 
      $ref: ../swagger/paths/contacts/{id}/get.yaml  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
